name: PluginPortal
version: '${version}'
main: link.portalbox.pluginportal.PluginPortal
api-version: 1.16
authors: [ Zestarr, Stephen, Shreyas Ayyengar ]
description: Plugin Package Manager
website: https://portalbox.link
